### ISSUE TITLE
Help users manipulate git by versioning the steps

### ISSUE THREAD

**Issue by tanohzana** [bnb/step-by-step-express#1]
I think it could be super cool to start from master, then create a first branch called `step-1` perhaps, then another for `step-2`, etc.

So that users are forced to experience git commands they might never  have used such as `checkout` or `cherry-pick`.

Indeed, another possibility would be to create a commit for each step, and then tell users to cherry-pick the next commit to advance.

Finally, it would make you rename your `step-X` folder into something closer to a real usecase. For instance `src` 😊

**Comment by bnb** [comment]
I definitely thought about doing this when I was building out the app, but in thinking about how I'd learned JavaScript, Node.js, and Express, I know I personally would have been put off by this added complexity when I was simply aiming to learn JavaScript.

I definitely think it's a good approach, but perhaps not one that perfectly fits in with the intended learning outcomes of this repository.

Thank you for the issue ❤️
